### ISSUE TITLE
3.1.1 version yanked

### ISSUE THREAD

**Issue by felipesabino** [kigster/colored2#4]
### Issue Description

Builds were broken overnight due to removal of gems from rubygems.

https://rubygems.org/gems/colored2/versions/3.1.1

> colored2 3.1.1
> This version has been yanked, and it is not available for download directly or for other gems that may have depended on it.

My legacy environments were fixed on version (`3.1.1`) and builds started breaking because `colored2` version `3.1.1` has been removed from rubygems.

Having an immutable build environment is crucial, so I believe removing old versions from rubygems in favor of new releases goes totally against it.

### Workaround

Need to execute on each repo/build that is broken

```
bundle update colored2
```

**Comment by kigster** [comment]
The version 3.1.1 contained broken permissions that were reported in another issue. 

Yanking gems versions from rubygems is meant specifically for this type of issue.

Please bundle update.
